import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "./navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="bumblebee" lang="en">
      <body className={inter.className}>
        <Theme>
          <div className="overflow-hidden">
            <Navbar />
          </div>
          {children}
        </Theme>
      </body>
    </html>
  );
}
