import type { Metadata } from "next";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "./navbar/page";
import Sidebar from "./sidebar/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="bumblebee" lang="en">
      <body className="w-screen">
        <Theme>
          <div className="flex flex-col">
            <div>
              <Navbar />
            </div>
            <div className="flex flex-row">
              <div className="sidebar flex-none ml-24 w-2/12 min-w-64 h-screen mr-5">
                <Sidebar />
              </div>
              <main className="flex-1 main p-5">{children}</main>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
