import type { Metadata } from "next";
import "./ui/globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Navbar from "./navbar/navbar";
import Sidebar from "./sidebar/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="bumblebee" lang="en">
      <body className="w-screen">
        <Theme>
          <div className="flex flex-col">
            <div>
              <Navbar />
            </div>
            <div className="flex flex-row">
              <div className="sidebar w-1/5 mr-5">
                <Sidebar />
              </div>
              <div className="flex-1 main">{children}</div>
            </div>
          </div>
        </Theme>
      </body>
    </html>
  );
}
